services:
  # Backend API service
  - type: web
    name: musichub-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "musichub-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://musichub-frontend.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://musichub-frontend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: musichub-db
          property: connectionString
    autoDeploy: true

databases:
  - name: musichub-db
    databaseName: musichub
    user: musichub_admin 